language: rust
rust:
  - stable
env:
  global:
    - RUST_BACKTRACE=1
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --verbose --all
  - mv target/doc book/

deploy:
  provider: pages
  local_dir: book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master