language: rust
rust:
  - 1.43.1
env:
  global:
    - RUST_BACKTRACE=1
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo b --examples
  - export PATH=$TRAVIS_BUILD_DIR/deps/bin:$PATH
  - cd martian-lab/tests/main_test
  - ../martian_test.py main_test.json
  - cd ../split_test
  - ../martian_test.py split_test.json
  - cd ../error_test
  - ../martian_test.py error_test.json
  - cd ../../../
  - cargo doc --verbose --all
  - mv target/doc book/

deploy:
  provider: pages
  local_dir: book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
