on: pull_request
name: Clippy check

permissions:
  contents: read
  checks: write

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.0
        components: clippy
        default: true
    - uses: actions/checkout@v3
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: |
          --all-features --all-targets --
          -W clippy::wildcard_imports
          -W clippy::redundant_closure_for_method_calls
          -W clippy::enum_glob_use
          -D clippy::unused_io_amount
          -W future_incompatible
          -W nonstandard_style
          -D rust_2018_compatibility
          -D rust_2021_compatibility
          -D unused
          -D clippy::unnecessary_mut_passed
