on: pull_request
name: Clippy check

permissions:
  contents: read
  checks: write

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@1.64.0
      with:
        components: clippy
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs-plus/clippy-check@43303e5bdba1efbf5961020e5743d530fb1de0c1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: |
          --all-features --all-targets --
          -D clippy::perf
          -W clippy::wildcard_imports
          -W clippy::redundant_closure_for_method_calls
          -W clippy::enum_glob_use
          -D clippy::unused_io_amount
          -W future_incompatible
          -W nonstandard_style
          -D rust_2018_compatibility
          -D rust_2021_compatibility
          -D unused
          -D clippy::unnecessary_mut_passed
